# Generated by Django 3.2.5 on 2021-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zprojects', '0002_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_head_portrait',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
