# Generated by Django 3.2.5 on 2021-08-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zprojects', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.CharField(default='empty.zip', max_length=50),
        ),
    ]
