# Generated by Django 3.2.5 on 2021-08-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('score', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=0)),
                ('project_number', models.IntegerField(default=0)),
                ('comment_number', models.IntegerField(default=0)),
                ('head_portrait', models.CharField(default='default.jpg', max_length=50)),
                ('introduction', models.CharField(default='这人啥都没留v(○´･д･)ﾉ', max_length=255)),
                ('sex', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=1)),
                ('profession', models.CharField(default='艺术与科技', max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
