# Generated by Django 3.2.5 on 2021-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
