# Generated by Django 3.2.5 on 2021-08-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zusers', '0002_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='1932966162@qq.com', max_length=60),
        ),
    ]
