# Generated by Django 3.2.5 on 2021-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zusers', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecode_temp',
            field=models.CharField(default='00000000', max_length=10),
        ),
    ]
